on: [push, pull_request]
jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Request Postman Echo GET
        uses: satak/webrequest-action@master
        with:
          url: https://my-json-server.typicode.com/typicode/demo/posts
          method: GET
