on: [push, pull_request]
jobs:
  request:
    runs-on: ubuntu-latest
    steps:
      - name: Request Postman Echo GET
        uses: ./
        with:
          url: 'https://api.glacierclient.net/update'
          method: 'GET'
